server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-authuser
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # define a estratégia de atualização do schema do banco de dados (update, create, create-drop, validate)
    show-sql: true # exibe consultas SQL na console
    properties:
      hibernate:
        format_sql: true # formata consultas SQL na console
        show_sql: true



